window.CRAWLER_GEAR_DATA = {
  items: [
    {name:'Steel Headband',slot:'carlHead',look:'headband',desc:'+16 max HP',stats:{player:{maxHp:16}}},
    {name:'Royal Tiara',slot:'donutHead',look:'tiara',desc:'+1 Donut shot',stats:{donut:{shots:1}}},
    {name:'Leather Jacket',slot:'carlBody',look:'jacket',desc:'+1 armor',stats:{player:{armor:1}}},
    {name:'Spiked Pauldrons',slot:'carlBody',look:'pauldrons',desc:'+2 armor, slightly ridiculous',stats:{player:{armor:2}}},
    {name:'Laser Pointer Collar',slot:'donutTrinket',look:'collar',desc:'Donut fires faster',stats:{donut:{fireRate:-4}},limits:{donutFireRateMin:12}},
    {name:'Sarcasm Holster',slot:'carlWeapon',look:'holster',desc:'+4 Carl damage',stats:{player:{damage:4}}},
    {name:'Chain Module',slot:'carlTrinket',look:'chain',desc:'Chance to arc lightning',stats:{player:{chainChance:0.18}}},
    {name:'Shotgun Frame',slot:'carlWeapon',look:'shotgun',desc:'Wider 3-shot spread',stats:{player:{fireRate:2}},special:{weaponStyle:'shotgun'}},
    {name:'Rifle Kit',slot:'carlWeapon',look:'rifle',desc:'Fast precise shots',stats:{player:{fireRate:-2,projSpeed:1.4}},limits:{playerFireRateMin:6},special:{weaponStyle:'rifle'}},
    {name:'Nine Lives Charm',slot:'carlTrinket',look:'charm',desc:'+1.1 regen/sec',stats:{player:{regen:1.1}},aura:{primary:'rgba(120,210,255,.95)',secondary:'rgba(255,230,120,.9)'}},
    {name:'Dungeon Sunglasses',slot:'carlHead',look:'sunglasses',desc:'+0.12 crit and dramatic shade',stats:{player:{crit:0.12}}},
    {name:'Fancy Necklace',slot:'donutTrinket',look:'necklace',desc:'+3 Donut damage',stats:{donut:{damage:3}},aura:{primary:'rgba(255,170,220,.95)',secondary:'rgba(215,245,255,.92)'}},
    {name:'Shiny Buttons',slot:'carlBody',look:'buttons',desc:'+8 max HP and +1 armor',stats:{player:{maxHp:8,armor:1}},aura:{primary:'rgba(255,240,120,.95)',secondary:'rgba(255,255,255,.85)'}},
    {name:'Velvet Cape Trim',slot:'donutHead',look:'trim',desc:'Donut missiles pierce once',stats:{donut:{pierce:1}}},
    {name:'Royal Anklet',slot:'carlTrinket',look:'anklet',desc:'+0.3 speed while barefoot',stats:{player:{speed:0.3}}},
    {name:'Star Brooch',slot:'carlHead',look:'brooch',desc:'+1 armor, mostly because it is pointy',stats:{player:{armor:1}},aura:{primary:'rgba(255,225,120,.95)',secondary:'rgba(120,210,255,.85)'}},
    {name:'Mirrored Aviators',slot:'carlHead',look:'aviators',desc:'+0.06 crit and +0.2 speed',stats:{player:{crit:0.06,speed:0.2}}},
    {name:'Gemmed Choker',slot:'donutTrinket',look:'choker',desc:'+2 Donut damage and +1 pierce',stats:{donut:{damage:2,pierce:1}},aura:{primary:'rgba(255,120,210,.95)',secondary:'rgba(255,245,170,.88)'}},
    {name:'Ruby Cufflinks',slot:'carlTrinket',look:'cufflinks',desc:'+2 Carl damage and a red aura',stats:{player:{damage:2}},aura:{primary:'rgba(255,105,105,.92)',secondary:'rgba(255,215,140,.78)'}},
    {name:'Moonstone Bow',slot:'donutHead',look:'moonbow',desc:'+1 Donut shot and a moonlit aura',stats:{donut:{shots:1}},aura:{primary:'rgba(195,175,255,.95)',secondary:'rgba(220,245,255,.82)'}},
    {name:'Barefoot Momentum Tape',slot:'carlBody',look:'wrap',desc:'+0.35 speed and +0.5 regen',stats:{player:{speed:0.35,regen:0.5}},aura:{primary:'rgba(140,220,255,.8)',secondary:'rgba(255,255,255,.6)'}},
    {name:'Inferno Shades',slot:'carlHead',look:'inferno',desc:'+3 Carl damage',stats:{player:{damage:3}},aura:{primary:'rgba(255,135,80,.95)',secondary:'rgba(255,215,140,.8)'}},
    {name:'Executive Lanyard',slot:'carlTrinket',look:'lanyard',desc:'+12 max HP and +0.04 crit',stats:{player:{maxHp:12,crit:0.04}}},
    {name:'Mall Ninja Anklet',slot:'carlTrinket',look:'ninjaanklet',desc:'+0.4 speed and +1 armor',stats:{player:{speed:0.4,armor:1}},aura:{primary:'rgba(170,255,220,.82)',secondary:'rgba(110,180,255,.72)'}},
    {name:'Starlight Bell',slot:'donutTrinket',look:'bell',desc:'Donut fires faster and hits harder',stats:{donut:{fireRate:-3,damage:2}},limits:{donutFireRateMin:11},aura:{primary:'rgba(255,215,120,.95)',secondary:'rgba(255,175,235,.85)'}},
    {name:'Velour Crown Bow',slot:'donutHead',look:'velourbow',desc:'+1 Donut shot and +2 damage',stats:{donut:{shots:1,damage:2}},aura:{primary:'rgba(255,140,215,.9)',secondary:'rgba(245,245,255,.8)'}},
    {name:'Oracle Monocle',slot:'carlHead',look:'monocle',desc:'+0.1 crit and faster shots',stats:{player:{crit:0.1,fireRate:-1}},limits:{playerFireRateMin:6}},
    {name:'Velvet Combat Harness',slot:'donutHead',look:'harness',desc:'+1 pierce and +2 damage',stats:{donut:{pierce:1,damage:2}}},
    {name:'Emergency Med Patch',slot:'carlBody',look:'medpatch',desc:'+18 max HP and +0.8 regen',stats:{player:{maxHp:18,regen:0.8}},aura:{primary:'rgba(140,255,190,.85)',secondary:'rgba(240,255,255,.7)'}},
    {name:'Boardroom Laser Sight',slot:'carlWeapon',look:'lasersight',desc:'+2 damage and faster shots',stats:{player:{damage:2,fireRate:-1}},limits:{playerFireRateMin:6}},
    {name:'Pearl Panic Collar',slot:'donutTrinket',look:'pearl',desc:'+1 Donut shot and faster fire',stats:{donut:{shots:1,fireRate:-2}},limits:{donutFireRateMin:11}}
  ]
};
